apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: nrp-2b-uat
data:
  application.yml: |
    server:
      port: 17091 
    
    spring:
      application:
        name: seata-server
    
    logging:
      config: classpath:logback-spring.xml
      file:
        path: ${user.home}/logs/seata
    
    console:
      user:
        username: seata
        password: seata
    
    seata:
      config:
        type: nacos
        nacos:
          server-addr: 192.168.0.206:8248
          namespace: 8422b4bf-8b04-406e-8295-39d4968b2ec4
          group: DEFAULT_GROUP
          data-id: seata.properties      
          #username:  
          #password: 
      registry:
        type: nacos
        nacos:  
          application: seata-server
          server-addr: 192.168.0.206:8248
          namespace: 8422b4bf-8b04-406e-8295-39d4968b2ec4
          group: DEFAULT_GROUP
          cluster: default
          #username:  
          #password: 
      security:
        secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
        tokenValidityInMilliseconds: 1800000
        ignore:
          urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login

  logback-spring.xml: | 
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="60 seconds" debug="false">
        <!-- Context listeners -->
        <contextListener class="io.seata.server.logging.listener.SystemPropertyLoggerContextListener"/>
    
        <!-- The conversion rules are copied from `defaults.xml` in the `spring-boot-xxx.jar` -->
        <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter" />
        <conversionRule conversionWord="wex" converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter" />
        <conversionRule conversionWord="wEx" converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter" />
        <!-- The custom conversion rules -->
        <conversionRule conversionWord="wEx2" converterClass="io.seata.server.logging.logback.ExtendedWhitespaceThrowableProxyConverter"/>
    
        <!-- common properties -->
        <springProperty name="PORT" source="server.port" defaultValue="7091"/>
        <springProperty name="APPLICATION_NAME" source="spring.application.name" defaultValue="seata-server"/>
    
    
        <!-- console-appender -->
        <include resource="logback/console-appender.xml"/>
    
        <!-- file-appender -->
        <include resource="logback/file-appender.xml"/>
    
        <!-- logstash-appender: off by default -->
        <!--<include resource="logback/logstash-appender.xml"/>-->
    
        <!-- kafka-appender: off by default -->
        <!--<include resource="logback/kafka-appender.xml"/>-->
    
        <root level="INFO">
            <!-- console-appender -->
            <appender-ref ref="CONSOLE"/>
    
            <!-- file-appender -->
            <appender-ref ref="FILE_ALL"/>
            <appender-ref ref="FILE_WARN"/>
            <appender-ref ref="FILE_ERROR"/>
    
            <!-- logstash-appender: off by default -->
            <!--<appender-ref ref="LOGSTASH"/>-->
    
            <!-- kafka-appender: off by default -->
            <!--<appender-ref ref="KAFKA"/>-->
        </root>
    </configuration>
